/* book.c generated by valac 0.26.0, the Vala compiler
 * generated from book.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_BOOK (book_get_type ())
#define BOOK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BOOK, Book))
#define BOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BOOK, BookClass))
#define IS_BOOK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BOOK))
#define IS_BOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BOOK))
#define BOOK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BOOK, BookClass))

typedef struct _Book Book;
typedef struct _BookClass BookClass;
typedef struct _BookPrivate BookPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _Book {
	GObject parent_instance;
	BookPrivate * priv;
};

struct _BookClass {
	GObjectClass parent_class;
};

struct _BookPrivate {
	gchar* title;
	gchar* isbn;
};


static gpointer book_parent_class = NULL;

GType book_get_type (void) G_GNUC_CONST;
#define BOOK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_BOOK, BookPrivate))
enum  {
	BOOK_DUMMY_PROPERTY
};
Book* book_new (const gchar* isbn, const gchar* title);
Book* book_construct (GType object_type, const gchar* isbn, const gchar* title);
void book_printISBN (Book* self);
void book_printTitle (Book* self);
static void book_finalize (GObject* obj);


Book* book_construct (GType object_type, const gchar* isbn, const gchar* title) {
	Book * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (isbn != NULL, NULL);
	g_return_val_if_fail (title != NULL, NULL);
	self = (Book*) g_object_new (object_type, NULL);
	_tmp0_ = isbn;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->isbn);
	self->priv->isbn = _tmp1_;
	_tmp2_ = title;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->title);
	self->priv->title = _tmp3_;
	return self;
}


Book* book_new (const gchar* isbn, const gchar* title) {
	return book_construct (TYPE_BOOK, isbn, title);
}


void book_printISBN (Book* self) {
	FILE* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	_tmp1_ = self->priv->isbn;
	fprintf (_tmp0_, "%s\n", _tmp1_);
}


void book_printTitle (Book* self) {
	FILE* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	_tmp1_ = self->priv->title;
	fprintf (_tmp0_, "%s\n", _tmp1_);
}


static void book_class_init (BookClass * klass) {
	book_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BookPrivate));
	G_OBJECT_CLASS (klass)->finalize = book_finalize;
}


static void book_instance_init (Book * self) {
	self->priv = BOOK_GET_PRIVATE (self);
}


static void book_finalize (GObject* obj) {
	Book * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_BOOK, Book);
	_g_free0 (self->priv->title);
	_g_free0 (self->priv->isbn);
	G_OBJECT_CLASS (book_parent_class)->finalize (obj);
}


GType book_get_type (void) {
	static volatile gsize book_type_id__volatile = 0;
	if (g_once_init_enter (&book_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BookClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) book_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Book), 0, (GInstanceInitFunc) book_instance_init, NULL };
		GType book_type_id;
		book_type_id = g_type_register_static (G_TYPE_OBJECT, "Book", &g_define_type_info, 0);
		g_once_init_leave (&book_type_id__volatile, book_type_id);
	}
	return book_type_id__volatile;
}



